"""create inventory risk table

Revision ID: 53823323d6a2
Revises: 81b2cd985abb
Create Date: 2026-08-23 20:50:53.121907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53823323d6a2'
down_revision: Union[str, Sequence[str], None] = '81b2cd985abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target_demand', sa.Float(), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=False),
    sa.Column('forecast_error', sa.Float(), nullable=False),
    sa.Column('absolute_error', sa.Float(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('forecast_demand', sa.Float(), nullable=False),
    sa.Column('projected_stock', sa.Float(), nullable=False),
    sa.Column('required_stock', sa.Float(), nullable=False),
    sa.Column('stock_surplus', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_risk_date'), 'inventory_risk', ['date'], unique=False)
    op.create_index(op.f('ix_inventory_risk_id'), 'inventory_risk', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_risk_product_id'), 'inventory_risk', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_risk_risk_level'), 'inventory_risk', ['risk_level'], unique=False)
    op.create_index(op.f('ix_inventory_risk_store_id'), 'inventory_risk', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_risk_store_id'), table_name='inventory_risk')
    op.drop_index(op.f('ix_inventory_risk_risk_level'), table_name='inventory_risk')
    op.drop_index(op.f('ix_inventory_risk_product_id'), table_name='inventory_risk')
    op.drop_index(op.f('ix_inventory_risk_id'), table_name='inventory_risk')
    op.drop_index(op.f('ix_inventory_risk_date'), table_name='inventory_risk')
    op.drop_table('inventory_risk')
    # ### end Alembic commands ###
