"""create unified priority table

Revision ID: 6d5acb41b01f
Revises: 53823323d6a2
Create Date: 2026-08-23 22:29:12.266212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5acb41b01f'
down_revision: Union[str, Sequence[str], None] = '53823323d6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('forecast_demand', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('edge_low_stock_count', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('from_store_id', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('unified_priority', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unified_priority_id'), 'unified_priority', ['id'], unique=False)
    op.create_index(op.f('ix_unified_priority_product_id'), 'unified_priority', ['product_id'], unique=False)
    op.create_index(op.f('ix_unified_priority_risk_level'), 'unified_priority', ['risk_level'], unique=False)
    op.create_index(op.f('ix_unified_priority_store_id'), 'unified_priority', ['store_id'], unique=False)
    op.create_index(op.f('ix_unified_priority_unified_priority'), 'unified_priority', ['unified_priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_priority_unified_priority'), table_name='unified_priority')
    op.drop_index(op.f('ix_unified_priority_store_id'), table_name='unified_priority')
    op.drop_index(op.f('ix_unified_priority_risk_level'), table_name='unified_priority')
    op.drop_index(op.f('ix_unified_priority_product_id'), table_name='unified_priority')
    op.drop_index(op.f('ix_unified_priority_id'), table_name='unified_priority')
    op.drop_table('unified_priority')
    # ### end Alembic commands ###
