"""create validated actions table

Revision ID: ecd0012b810b
Revises: 277dec79a822
Create Date: 2026-08-23 22:37:08.692646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd0012b810b'
down_revision: Union[str, Sequence[str], None] = '277dec79a822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validated_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_store_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('forecast_demand', sa.Float(), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validation_reason', sa.String(length=500), nullable=False),
    sa.Column('required_stock', sa.Float(), nullable=False),
    sa.Column('stock_after_transfer', sa.Float(), nullable=False),
    sa.Column('remaining_shortage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validated_actions_id'), 'validated_actions', ['id'], unique=False)
    op.create_index(op.f('ix_validated_actions_priority'), 'validated_actions', ['priority'], unique=False)
    op.create_index(op.f('ix_validated_actions_product_id'), 'validated_actions', ['product_id'], unique=False)
    op.create_index(op.f('ix_validated_actions_store_id'), 'validated_actions', ['store_id'], unique=False)
    op.create_index(op.f('ix_validated_actions_validation_status'), 'validated_actions', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validated_actions_validation_status'), table_name='validated_actions')
    op.drop_index(op.f('ix_validated_actions_store_id'), table_name='validated_actions')
    op.drop_index(op.f('ix_validated_actions_product_id'), table_name='validated_actions')
    op.drop_index(op.f('ix_validated_actions_priority'), table_name='validated_actions')
    op.drop_index(op.f('ix_validated_actions_id'), table_name='validated_actions')
    op.drop_table('validated_actions')
    # ### end Alembic commands ###
